"algo_name" : "PG"
"policy_type" : "mlp"
"default_session_ID" : "TST"
"activation_fun" : "F.selu"
"policy_optim" : "adam"
"log_tb_all" : False
"momentum" : 0.0
"learning_rate" : 0.003
"weight_decay" : 0.0000
"log_std_decay" : 0.0000
"iters" : 200000
"c_eps" : 0.2
"gamma" : 0.97
"batchsize" : 6
"alpha" : 0.99
"epsilon" : 1e-5
"ppo_update_iters" : 1
"lr_schedule" : "linear"
"normalize_rewards" : True
"policy_lastlayer_tanh" : False
"policy_hid_dim" : 196
"policy_memory_dim" : 96
"policy_grad_clip_value" : 0.9
"policy_residual_connection" : False