"algo_name" : "PG"
"policy_type" : "slp"
"gamma" : 0.99
"learning_rate" : 0.0001
"weight_decay" : 0.00001
"momentum" : 0.9
"alpha" : 0.99
"epsilon" : 1e-5
"ppo_update_iters" : 1
"lr_schedule" : "linear"
"normalize_rewards" : False
"policy_lastlayer_tanh" : False
"policy_hid_dim" : 256
"policy_memory_dim" : 128
"policy_grad_clip_value" : 0.5
"policy_residual_connection" : False