"algo_name" : "PG"
"policy_type" : "mlp_def"
"policy_optim" : "adam"
"default_session_ID" : "TST"
"activation_fun" : "F.leaky_relu"
"c_eps" : 0.2
"gamma" : 0.99
"batchsize" : 20
"learning_rate" : 0.0005
"weight_decay" : 0.0000
"momentum" : 0.0
"alpha" : 0.99
"epsilon" : 1e-5
"ppo_update_iters" : 1
"lr_schedule" : "linear"
"normalize_rewards" : False
"policy_lastlayer_tanh" : False
"policy_hid_dim" : 96
"policy_memory_dim" : 96
"policy_grad_clip_value" : 0.7
"policy_residual_connection" : False