"env_name" : "hexapod"
"max_steps" : 60
"step_counter" : True
"terrain_name" : "flat"
"training_mode" : "straight"
"velocity_control" : False
"force_target_velocity" : False
"forced_target_velocity" : 0.2
"sim_step" : 0.00417
"action_scaler" : 1
"env_width" : 60
"env_length" : 100
"env_change_prob" : 0.2
"randomize_env" : True
"max_actuator_velocity" : 3.0
"lateral_friction" : 1.2
"max_joint_force" : 1.6
"target_vel" : 0.3
"target_vell_nn_input" : 0
"target_vel_range" : [0.1, 0.5]
"sim_steps_per_iter" :  24
"mesh_scale_lat" : 0.1
"mesh_scale_vert" : 2
"perlin_height" : 40
"training_difficulty" : 1.0
"training_difficulty_increment" : 0.0001
"joints_rads_low" : [-0.5, -0.9, 0.2]
"joints_rads_high" : [0.5, 0.7, 1.4]
"target_proximity_threshold" : 0.5
"target_dispersal_distance" : 4
"urdf_name" : "hexapod_legsensor.urdf"
"seed" :
