"env_name" : "hexapod_wp_eef"
"controller_source" : "joystick" # joystick
"max_steps" : 900 # 700
"terrain_name" : "flat"
"training_mode" : "straight"
"velocity_control" : False
"force_target_velocity" : False
"forced_target_velocity" : 0.3
"sim_step" : 0.00417
"action_scaler" : 1
"env_width" : 60
"env_length" : 100
"env_change_prob" : 1.0
"step_counter" : 1
"latent_input" : 0
"act_input" : 0
"obs_input" : 1
"rew_input" : 0
"randomize_env" : False
"max_actuator_velocity" : 4.0
"lateral_friction" : 1.2
"max_joint_force" : 1.3
"target_vel" : 0.2
"target_vel_range" : [0.1, 0.5]
"sim_steps_per_iter" :  24
"mesh_scale_lat" : 0.1
"mesh_scale_vert" : 2
"perlin_height" : 34
"training_difficulty" : 1.0
"training_difficulty_increment" : 0.0001
"joints_rads_low" : [-0.5, -1.0, 0.4]
"joints_rads_high" : [0.5, 0.4, 1.0]
"target_proximity_threshold" : 0.5
"target_spawn_mu" : [1.5, 0.] # [1.5, 0.]
"target_spawn_sigma" : [0.0, 6.0] #[1.0, 4.0]
"angle_increment" : 0.006
"urdf_name" : "hexapod_normal.urdf"
"seed" :
"w_1": False
"w_2": True
"phase_scalar": .16   # 0.1
"phase_decay": .94 # 0.98
"z_aux_scalar" : 0.1 # 0.05
"inclination_pen" : 0.03
