"env_name" : "hexapod_wp_eef"
"controller_source" : "joystick" # joystick
"max_steps" : 80
"terrain_name" : "perlin"
"training_mode" : "straight"
"velocity_control" : False
"force_target_velocity" : False
"forced_target_velocity" : 0.3
"sim_step" : 0.00417
"action_scaler" : 1
"env_width" : 60
"env_length" : 100
"env_change_prob" : 1.0
"step_counter" : 1
"latent_input" : 0
"act_input" : 0
"obs_input" : 1
"rew_input" : 0
"randomize_env" : False
"max_actuator_velocity" : 3
"lateral_friction" : 2.0
"max_joint_force" : 1.2
"actuator_position_gain" : 0.5
"actuator_velocity_gain" : 0.5
"mass" : 1.6
"target_vel" : 0.25
"target_vel_range" : [0.1, 0.5]
"sim_steps_per_iter" :  12
"mesh_scale_lat" : 0.1
"mesh_scale_vert" : 2
"perlin_height" : 15
"training_difficulty" : 1.0
"training_difficulty_increment" : 0.0001
"joints_rads_low" : [-0.5, -1.0, 0.4]
"joints_rads_high" : [0.5, 0.4, 1.0]
"target_proximity_threshold" : 0.5
"target_spawn_mu" : [1.5, 0.] # [1.5, 0.]
"target_spawn_sigma" : [0.0, 4.0] # [1.0, 4.0]
"angle_increment" : 0.06
"urdf_name" : "hexapod_normal.urdf"
"seed" :
"w_1": False
"w_2": True
"phase_scalar": 0.175
"phase_offset_scalar": 1.2
"phase_decay": .94 # 0.98
"z_aux_scalar" : 0.0386 # 0.05
"x_mult_scalar" : 0.01992 # 0.05
"inclination_pen" : 0.00
"locomotion_mode" : "straight" # straight/cw/ccw