"env_name" : "hexapod"
"controller_source" : "joystick" # joystick
"max_steps" : 160
"terrain_name" : "perlin"
"sim_step" : 0.00417
"env_width" : 60
"env_length" : 100
"env_change_prob" : 1.0
"perlin_height" : 60
"mass" : 1.6
"lateral_friction" : 1.6
"max_joint_force" : 2.0
"actuator_position_gain" : 0.5
"actuator_velocity_gain" : 0.5
"max_actuator_velocity" : 6
"target_vel" : 0.2
"sim_steps_per_iter" :  12
"mesh_scale_lat" : 0.1
"mesh_scale_vert" : 2
"joints_rads_low" : [-0.5, -1.2, 0.2]
"joints_rads_high" : [0.5, 0.2, 1.6]
"target_proximity_threshold" : 0.3
"target_spawn_mu" : [4., 0.] # [1.5, 0.]
"target_spawn_sigma" : [0.0, 0.0] #[1.0, 4.0]
"urdf_name" : "hexapod_normal.urdf"
"seed" :
