"env_name" : "hexapod_obstacle"
"controller_source" : "joystick" # joystick
"max_steps" : 140
"terrain_name" : "obstacle"
"training_mode" : "straight"
"velocity_control" : False
"force_target_velocity" : False
"sim_step" : 0.00417
"action_scaler" : 1
"env_width" : 60
"env_length" : 100
"env_change_prob" : 1.0
"step_counter" : 1
"latent_input" : 0
"act_input" : 0
"obs_input" : 1
"rew_input" : 0
"randomize_env" : False
"max_actuator_velocity" : 3
"lateral_friction" : 2.0
"max_joint_force" : 1.5
"actuator_position_gain" : 0.5
"actuator_velocity_gain" : 0.5
"mass" : 1.8
"target_vel" : 0.6
"sim_steps_per_iter" :  12
"mesh_scale_lat" : 0.1
"mesh_scale_vert" : 2
"perlin_height" : 70
"obstacle_height" : 30
"training_difficulty" : 0.4
"training_difficulty_increment" : 0.003 # 0.0005
"velocities_and_torques" : False
"joints_rads_low" : [-0.6, -0.853, -0.60]
"joints_rads_high" : [0.6, 0.534, 0.9]
#"joints_rads_low_target" : [-0.6, -1.6, 0.7]
#"joints_rads_high_target" : [0.6, 0.5, 1.8]
"target_proximity_threshold" : 0.3
"target_spawn_mu" : [1.4, 0.] # [1.5, 0.]
"target_spawn_sigma" : [0.0, 0.0] # [1.0, 4.0]
"inclination_pen" : 0.0
"urdf_name" : "hexapod_normal.urdf"
"seed" :
