"algo_name" : "ES"
"policy_type" : "slp"
"n_hidden_layers" : 1
"default_session_ID" :
"activation_fun" : "T.tanh"
"log_tb_all" : False
"cma_std" : 0.24
"iters" : 50
"algo" : "cma" # optuna/cma
"preload" : False
"save_agent" : True
"optuna_trials" : 150
"weight_init_bnd" : 1.
"policy_hid_dim" : 8
"policy_residual_connection" : True
"verbose" : 1