"algo_name" : "ES"
"policy_type" : "mlp_es"
"n_hidden_layers" : 1
"default_session_ID" : "TST"
"activation_fun" : "T.tanh"
"log_tb_all" : False
"cma_std" : 0.003
"iters" : 150
"weight_init_bnd" : 1.
"policy_hid_dim" : 8
"policy_residual_connection" : True