"algo_name" : "ES"
"policy_type" : "slp"
"default_session_ID" : "TST"
"activation_fun" : "F.leaky_relu"
"log_tb_all" : True
"cma_std" : 0.2
"iters" : 300
"batchsize" : 20
"weight_decay" : 0.0000
"init_log_std_value" : -0.9
"weight_init_bnd" : 1.
"normalize_rewards" : False
"policy_lastlayer_tanh" : False
"policy_hid_dim" : 32
"policy_memory_dim" : 64
"policy_residual_connection" : False