"algo_name" : "A2C"
"policy_name" : "MlpPolicy" # "MlpLstmPolicy", "MlpPolicy", "CustomAC"
"default_session_ID" :
"n_envs" : 6
"iters" : 10000000
"gamma" : 0.99
"n_steps" : 60
"vf_coef" : 0.5
"ent_coef" : 0.0000057
"max_grad_norm" : 0.5
"learning_rate" : 0.0003
"alpha" : 0.99
"epsilon" : 0.00001
"lr_schedule" : 'linear'
"verbose" : 1
"full_tensorboard_log" : False
"policy_lastlayer_tanh" : False
"policy_hid_dim" : 64
"policy_memory_dim" : 128
"policy_grad_clip_value" : 1.0
"policy_residual_connection" : False
"norm_obs" : True
"norm_reward" : True