"algo_name" : "A2C"
"policy_name" : "MlpPolicy"
"default_session_ID" :
"n_envs" : 6
"iters" : 20000000
"gamma" : 0.99
"n_steps" : 20
"vf_coef" : 0.5
"ent_coef" : 0.00000 # Should be very low
"max_grad_norm" : 0.4
"learning_rate" : 0.0001
"alpha" : 0.99
"epsilon" : 0.00001
"lr_schedule" : 'linear'
"verbose" : 1
"full_tensorboard_log" : False
"policy_lastlayer_tanh" : False
"policy_hid_dim" : 96
"policy_memory_dim" : 64
"policy_residual_connection" : False
"norm_obs" : True
"norm_reward" : True
"w_1" : True
"w_2" : False
"phase_scalar" : .5