"algo_name" : "A2C"
"policy_name" : "MlpPolicy"
"default_session_ID" :
"n_envs" : 6
"iters" : 16000000
"gamma" : 0.997
"n_steps" : 36
"vf_coef" : 0.5
"ent_coef" : 0.00000 # Should be very low
"max_grad_norm" : 0.5
"learning_rate" : "lambda x : x * 0.0004" # 0.00026
"alpha" : 0.99
"epsilon" : 0.00001
"lr_schedule" : 'linear'
"verbose" : 2
"tensorboard_log" : True
"full_tensorboard_log" : False
"policy_lastlayer_tanh" : False
"policy_hid_dim" : 96
"policy_memory_dim" : 64
"policy_residual_connection" : False
"norm_obs" : False
"norm_reward" : False
"use_sde" : False
"dummy_vec_env" : False
