"algo_name" : "A2C"
"default_session_ID" :
"n_envs" : 6
"iters" : 7000000
"gamma" : 0.99
"n_steps" : 30
"vf_coef" : 0.5
"ent_coef" : 0.0
"max_grad_norm" : 0.5
"learning_rate" : 0.0007
"alpha" : 0.99
"epsilon" : 0.00001
"lr_schedule" : 'linear'
"verbose" : 1
"full_tensorboard_log" : False
"policy_kwargs" : "dict(layers=[256, 256])"
"policy_lastlayer_tanh" : False
"policy_hid_dim" : 256
"policy_memory_dim" : 128
"policy_grad_clip_value" : 1.0
"policy_residual_connection" : False