"algo_name" : "A2C"
"policy_name" : "MlpPolicy"
"default_session_ID" :
"n_envs" : 6
"iters" : 7000000
"gamma" : 0.999
"n_steps" : 20
"vf_coef" : 0.6
"ent_coef" : 0.00001 # Should be very low
"max_grad_norm" : 0.45
"learning_rate" : 0.0003
"alpha" : 0.99
"epsilon" : 0.00001
"lr_schedule" : 'linear'
"verbose" : 1
"full_tensorboard_log" : False
"policy_lastlayer_tanh" : False
"policy_hid_dim" : 256
"policy_memory_dim" : 256
"policy_residual_connection" : False
"norm_obs" : False
"norm_reward" : True