"algo_name" : "PG"
"gamma" : 0.99
"learning_rate" : 0.0001
"alpha" : 0.99
"epsilon" : 1e-5
"lr_schedule" : "linear"
"policy_lastlayer_tanh" : False
"policy_hid_dim" : 256
"policy_memory_dim" : 128
"policy_grad_clip_value" : 1.0
"policy_residual_connection" : False