"algo_name" : "TD3"
"policy_name" : "MlpPolicy" # "MlpLstmPolicy", "MlpPolicy"
"default_session_ID" :
"n_envs" : 1
"iters" : 800000
"gamma" : 0.99
"learning_rate" : "lambda x : x * 0.001"
"buffer_size" : 100000
"learning_starts" : 30000
"batch_size" : 256
"tau" : 0.005
"policy_delay" : 2
"target_policy_noise" : 0.1
"target_noise_clip" : 0.1
"policy_hid_dim" : 196
"verbose" : 1
"tensorboard_log" : True
"ou_sigma" : 0.9
"ou_theta" : 0.1
"ou_dt" : 0.1
"ent_coef" : 0.001
