"algo_name" : "TD3"
"policy_name" : "MlpPolicy"
"default_session_ID" :
"n_envs" : 1
"iters" : 1000000
"gamma" : 0.99
"learning_rate" : 0.0007
"buffer_size" : 1000000
"learning_starts" : 10000
"train_freq" : 1000
"gradient_steps" : 1000
"batch_size" : 128
"tau" : 0.005
"policy_delay" : 2
"action_noise" : None
"target_policy_noise" : 0.2
"target_noise_clip" : 0.5
"verbose" : 1
"policy_kwargs" : {layers : [256, 256]}