"env_name" : buggy
"controller_source" : "joystick" # nn/joystick
"max_steps" : 1800
"step_counter" : False
"latent_input" : False
"action_input" : False
"rew_input" : False
"randomize_env" : False
"sim_timestep" : 0.006
"env_change_prob" : 0.1
"target_proximity_threshold" : 0.6
"target_dispersal_distance" : 4
"urdf_name" : buggy_diff.urdf
"seed" :
"wp_sequence" : "rnd" # two_pole, four_pole, rnd
