"env_name" : buggy
"max_steps" : 300
"step_counter" : True
"latent_input" : False
"action_input" : False
"randomize_env" : False
"sim_timestep" : 0.01
"env_change_prob" : 0.1
"target_proximity_threshold" : 0.2
"target_dispersal_distance" : 8
"urdf_name" : buggy.urdf
"seed" :
