"env_name" : buggy
"controller_source" : "joystick" # nn/joystick
"sim_timestep" : 0.005
"lateralFriction" : 0.5
"velocity_scalar" : 200
"steering_scalar" : 0.6
"max_force" : 10
"mass" : 1
"urdf_name" : buggy_diff.urdf
"seed" :

