"n_trn_iters" : 100000
"input_dim" : 5
"output_dim" : 3
"hidden_dim" : 64
"non_linearity" : "nn.LeakyReLU" #  nn.ReLU, nn.ReLU6, nn.LeakyReLU, nn.ELU, nn.Tanh
"initialization" : ""
"weight_decay" : 0.0001
"optimizer" : adam
"learning_rate" : 0.007
"trn_val_ratio" : 0.8
"trn_batchsize" : 64
"verbose": True
"policy_grad_clip_value": 0.5
