"n_trn_iters" : 1000
"input_dim" : 5
"output_dim" : 4
"hidden_dim" : 32
"non_linearity" : "nn.ReLU" #  nn.ReLU, nn.ReLU6, nn.LeakyReLU, nn.ELU, nn.Tanh
"initialization" : ""
"weight_decay" : 0.0001
"optimizer" : adam
"learning_rate" : 0.001
"trn_val_ratio" : 0.8
"trn_batchsize" : 128
