"env_name" : "quadrotor_stab"
"controller_source" : "nn" # nn/pid
"target_vel_source" : "still" # still/rnd/joystick
"max_steps" : 500
"step_counter" : False
"latent_input" : False
"action_input" : True
"rew_input" : False
"randomize_env" : True
"env_change_prob" : 0.5
"sim_timestep" : 0.01
"action_scaler" : 1.0
"propeller_parasitic_torque_coeff" : 1.0
"starting_pos" : [0, 0, 2.0]
"target_pos" : [0, 0, 2.0]
"disturbance_intensity" : 7 # 10 for effect
"disturbance_frequency" : 0.005 # 0.005
"urdf_name" : quadrotor.urdf
"seed" :
"joystick_mapping" : [2,3,0,1] # [0,1,2,3] for 3D pro, [2,3,0,1] for xbox, [] for Logitech
"p_roll" : 0.2
"p_pitch" : 0.2
"p_yaw" : 0.2
"d_roll" : 3.0
"d_pitch" : 3.0
"d_yaw" : 0.1
