"env_name" : "quadrotor_stab"
"controller_source" : "pid" # nn/pid
"target_vel_source" : "joystick" # still/rnd/joystick
"rnd_init" : True
"max_steps" : 500
"step_counter" : 1
"latent_input" : 0
"act_input" : 0
"obs_input" : 1
"rew_input" : 0
"randomize_env" : False
"env_change_prob" : 0.5
"sim_timestep" : 0.01
"action_scaler" : 1.0
"propeller_parasitic_torque_coeff" : 1.0
"starting_pos" : [0, 0, 2.0]
"target_pos" : [0, 0, 2.0]
"disturbance_intensity" : 5 # 10 for effect
"disturbance_frequency" : 0.00 # 0.005
"default_mass" : 0.8
"default_boom_length" : 0.15
"default_motor_spinup_speed" : 0.1
"default_motor_force_multiplier" : 8
"urdf_name" : quadrotor.urdf
"seed" :
"joystick_mapping" : [2,3,0,1] # [0,1,2,3] for 3D pro, [3,4,0,1] for xbox, [2,3,0,1]s for Logitech
"p_roll" : 0.2
"p_pitch" : 0.2
"p_yaw" : 0.2
"d_roll" : 3.0
"d_pitch" : 3.0
"d_yaw" : 0.1
"i_roll" : -0.00
"i_pitch" : -0.00
"input_transport_delay" : 0
"output_transport_delay" : 0
"raw_act_smoothness_pen" : 0.001
