"env_name" : "quadrotor_stab"
"controller_source" : "nn" # nn/pid
"target_vel_source" : "joystick" # still/rnd/joystick
"max_steps" : 500
"step_counter" : True
"latent_input" : False
"action_input" : False
"randomize_env" : False
"env_change_prob" : 0.1
"sim_timestep" : 0.01
"action_scaler" : 1.0
"propeller_parasitic_torque_coeff" : 1.0
"starting_pos" : [0, 0, 2.0]
"target_pos" : [0, 0, 2.0]
"disturbance_intensity" : 10
"disturbance_frequency" : 0.000 # 0.005
"urdf_name" : quadrotor.urdf
"seed" :
"joystick_mapping" : [0,1,2,3] # [0,1,2,3] for 3D pro, [2,3,0,1] for xbox
