"env_name" : quadrotor
"max_steps" : 1000
"step_counter" : True
"latent_input" : False
"action_input" : False
"is_variable" : False
"sim_timestep" : 0.00417
"propeller_parasitic_torque_coeff" : 0.3
"env_change_prob" : 0.1
"urdf_name" : quadrotor.urdf
"seed" :
