"algo_name" : "AC"
"policy_type" : "mlp"
"default_session_ID" :
"activation_fun" : "T.tanh"
"policy_optim" : "adam"
"log_tb" : False
"save_policy" : True
"n_envs" : 6
"init_log_std_value" : -0.9
"weight_init_bnd" : 0.3
"momentum" : 0.0
"policy_learning_rate" : 0.0001
"vf_learning_rate" : 0.0003
"weight_decay" : 0.0001
"n_total_steps_train" : 2000000
"gamma" : 0.99
"batchsize" : 2
"policy_hid_dim" : 64
"vf_hid_dim" : 256
"policy_grad_clip_value" : 0.7
"policy_residual_connection" : False
"advantages_MC" : True
"norm_obs" : False
"norm_reward" : True