"algo_name" : "AC"
"policy_type" : "mlp"
"default_session_ID" :
"activation_fun" : "F.tanh"
"policy_optim" : "adam"
"log_tb" : False
"momentum" : 0.0
"learning_rate" : 0.0003
"weight_decay" : 0.0001
"n_total_steps_train" : 10000
"gamma" : 0.99
"batchsize" : 4
"policy_hid_dim" : 96
"vf_hid_dim" : 96
"policy_grad_clip_value" : 0.5
"policy_residual_connection" : False