"algo_name" : "AC"
"policy_type" : "mlp"
"default_session_ID" :
"activation_fun" : "T.tanh"
"policy_optim" : "adam"
"log_tb" : False
"save_policy" : True
"n_envs" : 6
"weight_init_bnd" : 1.0
"momentum" : 0.0
"policy_learning_rate" : 0.0003
"vf_learning_rate" : 0.0005
"init_log_std_value" : -0
"weight_decay" : 0.0000
"n_total_steps_train" : 3000000
"n_steps_per_checkpoint" : 1000000
"n_steps_per_update" : 100
"gamma" : 0.99
"batchsize" : 6
"policy_hid_dim" : 64
"vf_hid_dim" : 128
"policy_grad_clip_value" : 0.5
"policy_residual_connection" : False
"norm_obs" : False
"norm_reward" : False