"env_name" : cartpole_balance
"max_steps" : 300
"step_counter" : False
"latent_input" : False
"action_input" : False
"randomize_env" : False
"sim_timestep" : 0.02
"env_change_prob" : 0.1
"velocity_scaler" : 100
"max_force" : 10
"target_proximity_threshold" : 0.2
"target_dispersal_distance" : 8
"urdf_name" : cartpole_balance.urdf
"seed" :
