"algo_name" : "MAML"
"policy_type" : "mlp"
"default_session_ID" : "TST"
"activation_fun" : "F.selu"
"log_tb_all" : False
"batchsize" : 4
"batchsize_meta" : 6
"k" : 1
"gamma" : 0.99
"n_steps" : 70
"learning_rate" : 0.0007
"learning_rate_meta" : 0.001
"momentum" : 0.9
"momentum_meta" : 0.9
"w_decay" : 0.001
"w_decay_meta" : 0.001
"lr_schedule" : "linear"
"normalize_rewards" : False
"policy_lastlayer_tanh" : False
"policy_hid_dim" : 128
"policy_memory_dim" : 128
"policy_grad_clip_value" : 0.5
"policy_residual_connection" : False
